image: fedora:latest

before_script:
  - dnf install npm translate-toolkit -y 

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm install
    - ./i18n_gen_yml.sh # run at build time to create temporary yml files from weblate po files.
    - npm run generate
    - rm -rf ./public
    - mv .output/public ./public
  artifacts:
    expire_in: 1 day # unless marked as keep from job page
    paths:
      - public
  only:
    - develop # only build develop branch to test deploy. Feature branches are not built, main is hosted on Fedora CDN.



# update_pos_if_yaml_changed:
#   script:
#     - ./i18n_gen_pot.sh # run whenever changes to /content. commit pot files to repo.
#   artifacts:
#     expire_in: 1 day # unless marked as keep from job page
#   only:
#     - develop # only build develop branch to test deploy. Feature branches are not built, main is hosted on Fedora CDN.
