const EC2_regions = {
  "us-east-1": "US East (N. Virginia)",
  "us-east-2": "US East (Ohio)",
  "us-west-1": "US West (N. California)",
  "us-west-2": "US West (Oregon)",
  "af-south-1": "Africa (Cape Town)",
  "ap-east-1": "Asia Pacific (Hong Kong)",
  "ap-south-1": "Asia Pacific (Mumbai)",
  "ap-south-2": "Asia Pacific (Hyderabad)",
  "ap-northeast-1": "Asia Pacific (Tokyo)",
  "ap-northeast-2": "Asia Pacific (Seoul)",
  "ap-northeast-3": "Asia Pacific (Osaka)",
  "ap-southeast-1": "Asia Pacific (Singapore)",
  "ap-southeast-2": "Asia Pacific (Sydney)",
  "ap-southeast-3": "Asia Pacific (Jakarta)",
  "ap-southeast-4": "Asia Pacific (Melbourne)",
  "ap-southeast-5": "Asia Pacific (Malaysia)",
  "ca-central-1": "Canada (Central)",
  "ca-west-1": "Canada West (Calgary)",
  "eu-central-1": "Europe (Frankfurt)",
  "eu-central-2": "Europe (Zurich)",
  "eu-west-1": "Europe (Ireland)",
  "eu-west-2": "Europe (London)",
  "eu-west-3": "Europe (Paris)",
  "eu-south-1": "Europe (Milan)",
  "eu-south-2": "Europe (Spain)",
  "eu-north-1": "Europe (Stockholm)",
  "il-central-1": "Israel (Tel Aviv)",
  "me-south-1": "Middle East (Bahrain)",
  "me-central-1": "Middle East (UAE)",
  "sa-east-1": "South America (São Paulo)",
};

const Azure_regions = {
  southafricanorth: "(Africa) South Africa North",
  australiaeast: "(Asia Pacific) Australia East",
  centralindia: "(Asia Pacific) Central India",
  eastasia: "(Asia Pacific) East Asia",
  japaneast: "(Asia Pacific) Japan East",
  koreacentral: "(Asia Pacific) Korea Central",
  southeastasia: "(Asia Pacific) Southeast Asia",
  canadacentral: "(Canada) Canada Central",
  northeurope: "(Europe) North Europe",
  uksouth: "(Europe) UK South",
  westeurope: "(Europe) West Europe",
  francecentral: "(Europe) France Central",
  switzerlandnorth: "(Europe) Switzerland North",
  germanywestcentral: "(Europe) Germany West Central",
  italynorth: "(Europe) Italy North",
  norwayeast: "(Europe) Norway East",
  swedencentral: "(Europe) Sweden Central",
  polandcentral: "(Europe) Poland Central",
  spaincentral: "(Europe) Spain Central",
  brazilsouth: "(South America) Brazil South",
  mexicocentral: "(Mexico) Mexico Central",
  uaenorth: "(Middle East) UAE North",
  israelcentral: "(Middle East) Israel Central",
  qatarcentral: "(Middle East) Qatar Central",
  eastus: "(US) East US",
  eastus2: "(US) East US 2",
  centralus: "(US) Central US",
  southcentralus: "(US) South Central US",
  westus2: "(US) West US 2",
  westus3: "(US) West US 3",
};

export { Azure_regions, EC2_regions };
