backend:
  name: gitlab
  repo: fedora/websites-apps/fedora-websites/fedora-websites-3.0
  # Do more research on https://www.netlifycms.org/docs/gitlab-backend/
  #  auth_type: pkce # Required for pkce
  #  app_id: 758719d1c68529b4acc2f2f3556cad1a8bba916f63094fc377afcb31d25bf349 # Application ID from your GitLab settings
  branch: cms-rewrite
  squash_merges: true
local_backend: true

# Docs for Editorial Workflow: https://www.netlifycms.org/docs/configuration-options/
#publish_mode: editorial_workflow
# Deploy Preview Links Docs: https://www.netlifycms.org/docs/deploy-preview-links/
show_preview_links: true

# Assets
media_folder: "assets/images"

### Table of Contents ###
# Workstation Pages - 25
# IoT Pages         - 110
# Server Pages      - 195
###                   ###

collections:
  #####################
  # Workstation Pages #
  #####################
  - name: "workstation" # Used in routes, e.g., /admin/collections/blog
    label: "Workstation Pages" # Used in the UI
    label_singular: "Workstation Page"
    folder: "editions/workstation" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: true
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "The page title as seen in the url. ie: workstation/community",
        }
      - {
          label: "Headline",
          name: "headline",
          widget: "string",
          hint: "The h1 text in the page header",
        }
      - {
          label: "Subheadline",
          name: "subheadline",
          widget: "textarea",
          hint: "Page header secondary text",
        }
      - {
          label: "Header Images",
          name: "header_images",
          widget: "image",
          hint: "Add background and foreground images to the header",
        }
      - label: "Page Sections"
        label_singular: "Page Section"
        name: "body"
        hint: "Main sections of page content, generally grouped by h2 headings"
        summary: "Page Section"
        widget: "list"
        minimize_collapsed: true
        max: 8
        allow_add: true
        fields:
          - {
              label: "Headline",
              name: "headline",
              widget: "string",
              hint: "The section's main title",
            }
          - {
              label: "Subheadline",
              name: "subheadline",
              widget: "text",
              hint: "The section's main subtitle",
            }
          - {
              label: "Images",
              singular_label: "image",
              name: "images",
              widget: "image",
            }
          - {
              label: "Section Content",
              name: "content",
              widget: "markdown",
              hint: "Add the majority of your content here",
              buttons:
                [
                  "bold",
                  "italic",
                  "link",
                  "code",
                  "heading-three",
                  "heading-four",
                  "heading-five",
                  "quote",
                  "bulleted-list",
                  "numbered-list",
                ],
              editor_components: ["image", "code-blocks"],
              sanitize_preview: true,
            }
  ####################
  # Fedora IOT Pages #
  ####################
  - name: "iot" # Used in routes
    label: "Iot Pages" # Used in the UI
    label_singular: "Iot Page"
    folder: "editions/iot" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: true
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "The page title as seen in the url. ie: workstation/community",
        }
      - {
          label: "Headline",
          name: "headline",
          widget: "string",
          hint: "The h1 text in the page header",
        }
      - {
          label: "Subheadline",
          name: "subheadline",
          widget: "textarea",
          hint: "Page header secondary text",
        }
      - {
          label: "Header Images",
          name: "header_images",
          widget: "image",
          hint: "Add background and foreground images to the header",
        }
      - label: "Page Sections"
        label_singular: "Page Section"
        name: "body"
        hint: "Main sections of page content, generally grouped by h2 headings"
        summary: "Page Section"
        widget: "list"
        minimize_collapsed: true
        max: 8
        allow_add: true
        fields:
          - {
              label: "Headline",
              name: "headline",
              widget: "string",
              hint: "The section's main title",
            }
          - {
              label: "Subheadline",
              name: "subheadline",
              widget: "text",
              hint: "The section's main subtitle",
            }
          - {
              label: "Images",
              singular_label: "image",
              name: "images",
              widget: "image",
            }
          - {
              label: "Section Content",
              name: "content",
              widget: "markdown",
              hint: "Add the majority of your content here",
              buttons:
                [
                  "bold",
                  "italic",
                  "link",
                  "code",
                  "heading-three",
                  "heading-four",
                  "heading-five",
                  "quote",
                  "bulleted-list",
                  "numbered-list",
                ],
              editor_components: ["image", "code-blocks"],
              sanitize_preview: true,
            }
  #######################
  # Fedora Server Pages #
  #######################
  - name: "Server" # Used in routes
    label: "Server Pages" # Used in the UI
    label_singular: "Server Page"
    folder: "editions/iot" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: true
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "The page title as seen in the url. ie: workstation/community",
        }
      - {
          label: "Headline",
          name: "headline",
          widget: "string",
          hint: "The h1 text in the page header",
        }
      - {
          label: "Subheadline",
          name: "subheadline",
          widget: "textarea",
          hint: "Page header secondary text",
        }
      - {
          label: "Header Images",
          name: "header_images",
          widget: "image",
          hint: "Add background and foreground images to the header",
        }
      - label: "Page Sections"
        label_singular: "Page Section"
        name: "body"
        hint: "Main sections of page content, generally grouped by h2 headings"
        summary: "Page Section"
        widget: "list"
        minimize_collapsed: true
        max: 8
        allow_add: true
        fields:
          - {
              label: "Headline",
              name: "headline",
              widget: "string",
              hint: "The section's main title",
            }
          - {
              label: "Subheadline",
              name: "subheadline",
              widget: "text",
              hint: "The section's main subtitle",
            }
          - {
              label: "Images",
              singular_label: "image",
              name: "images",
              widget: "image",
            }
          - {
              label: "Section Content",
              name: "content",
              widget: "markdown",
              hint: "Add the majority of your content here",
              buttons:
                [
                  "bold",
                  "italic",
                  "link",
                  "code",
                  "heading-three",
                  "heading-four",
                  "heading-five",
                  "quote",
                  "bulleted-list",
                  "numbered-list",
                ],
              editor_components: ["image", "code-blocks"],
              sanitize_preview: true,
            }
