backend:
  name: gitlab
  repo: fedora/websites-apps/fedora-websites/fedora-websites-3.0
  auth_type: pkce # Required for pkce
  app_id: 758719d1c68529b4acc2f2f3556cad1a8bba916f63094fc377afcb31d25bf349 # Application ID from your GitLab settings  
  branch: cms-dev
local_backend: true
# publish_mode: editorial_workflow
# Add Fedora Logo to the UI

display_url: https://fedora.gitlab.io/websites-apps/fedora-websites/fedora-websites-3.0/
# Asset Organization
media_folder: "public/assets/images/"
public_folder: "public/assets/images/"

# Collections starter code
collections:
  - name: posts
    preview_path: "blog/{{year}}/{{month}}/{{slug}}"
    folder: "content/editions"
    fields:
        - label: "Title"
          name: "title"
          widget: "string"
    label: "Posts"
  # File Collection for individual Pages
  - label: "Workstation Edition"
    name: "workstation"
    files:
      - label: "Index Page"
        name: "index"
        file: "content/editions/workstation/index.yml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string" 
      - label: "Download Page"
        name: "download"
        file: "content/editions/workstation/download.yml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
  # IOT Edition Pages
  - label: "IoT Edition"
    name: "iot"
    files: 
      - label: "Index Page"
        name: "index"
        file: "content/editions/iot/index.yml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "heroImage", widget: "image"}
      - label: "Download Page"
        name: "download"
        file: "content/editions/iot/download.yml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
  - label: "Server Edition"
    name: "server"
    files: 
      - label: "Index Page"
        name: "index"
        file: "content/editions/server/index.yml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
      - label: "Download Page"
        name: "download"
        file: "content/editions/server/download.yml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"  